// Generated by ts-to-zod
import { z } from "zod";

export const tableSettingsSchema = z.object({
  url: z.string(),
  export: z.boolean().optional(),
  editButton: z.boolean().optional(),
  deleteButton: z.boolean().optional(),
  newRecordButton: z.boolean().optional(),
  title: z.string(),
  transformData: z.boolean().optional(),
  editCallBack: z.boolean().optional(),
  newCallBack: z.boolean().optional(),
  softDelete: z.boolean().optional(),
});

export const tableColumnSchema = z.object({
  field: z.string(),
  labelId: z.string(),
  sort: z.boolean().optional(),
  filter: z.union([z.literal("search"), z.literal("select")]).optional(),
  sourceUrl: z.string().optional(),
  optionLabel: z.string().optional(),
  filterDataKey: z.string().optional(),
  filterKey: z.string().optional(),
  type: z.string().optional(),
  translate: z.boolean().optional(),
});

export const tableViewConfigSchema = z.object({
  settings: tableSettingsSchema,
  columns: z.array(tableColumnSchema),
});
